[package]
name = "aoc2020"
version = "0.1.0"
authors = ["kolmodin"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "6.0.1"
priority-queue = "1.0.3"
itertools = "0.9.0"